### ISSUE TITLE
Easyslider To be consistent with Anysurfer

### ISSUE THREAD

**Issue by smoussiaux** [collective/collective.easyslider#10]
Hello,

To be consistent with Anysurfer (http://www.anysurfer.be/en , a non-profit organisation for the visually impaired with close connections to other associations who plead for the interests of the disabled. We strive for a more accessible internet for all users, including those with a disability.), the "pause" button must be accessible with the keyboard. It's a requierement.

To do this, I replace 

```
<div id="pauseplay"></div>
```

by

```
<button type="button"></button>
```

and, to be completly effective, I also change references to that id in easyslider.js.

Of course, the CSS must be adjusted.

Stéphane Moussiaux

**Comment by vangheem** [comment]
Will anchor tags work? Do you have a merge request you can submit?

**Comment by smoussiaux** [comment]
with the anchor tags does not work wel, there is a problem of the slider restart

**Comment by toutpt** [comment]
fixed by 2e55dac3b8276d1cff3fdfca8de2254d369cc3f5
