### ISSUE TITLE
Breaks ZMI after removing c.easyslider from buildout

### ISSUE THREAD

**Issue by ida** [collective/collective.easyslider#17]
After removing c.easyslider from the buildout-config, calling the ZMI will result in both frames with:

```
Error Type: TypeError
Error Value: ("'ExtensionClass.ExtensionClass' object is not iterable", <function Provides at 0x134d2e60>, (<class 'Products.ATContentTypes.content.document.ATDocument'>, <class 'collective.easyslider.interfaces.ISliderPage'>))
```

**Comment by vangheem** [comment]
Is that the full stack trace?

What version?

Did you uninstall it from the instance first?

If that uninstall didn't work quite right, did you try running the uninstall profile?

**Comment by ida** [comment]
I installed a site with c.easyslider, then deleted the site, then removed c.easyslider from buildout. The error occured on the very Zope-root-level, not on a site. Yet, this scenario is probably negligible.

**Comment by vangheem** [comment]
Wow, that's really bizarre. Do you have the full traceback?

**Comment by ida** [comment]
Nope sorry, deleted the DB already and cannot reproduce. With the steps described above nothing breaks at all, now. Cannot exclude that other third-party-add-ons were interfering, also. Feel free to close as invalid.
