### ISSUE TITLE
Add new slide for a page

### ISSUE THREAD

**Issue by fmonaco** [collective/collective.easyslider#9]
I can't create a slice in slide, when i click on "add new slice", i aM  redirected to the folder view

**Comment by vangheem** [comment]
Are there javascript errors? Any errors in console? What version of easyslider?

**Comment by fmonaco** [comment]
Hi,
no javascript errors, no errors in console, and I use easyslider 1.0 (Jquery 1.4.4)
best regard,Fabrice

Date: Wed, 19 Sep 2012 06:09:38 -0700

**Comment by vangheem** [comment]
Oops, sorry, a couple more questions.
- What version of Plone?
- Any other addons?

I can't reproduce this with normal setup.

**Comment by fmonaco** [comment]
Hi,

I have attached the configuration files my installation of plone

thank,
Fabrice

Date: Thu, 20 Sep 2012 06:36:00 -0700

**Comment by vangheem** [comment]
I don't see any attached files here on github--in fact, I don't think that's possible. Going to close for now until I can get more information to actually try and reproduce.
